# Generated by Django 5.2.8 on 2025-11-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('isbn', models.IntegerField()),
                ('total_copy', models.PositiveIntegerField()),
                ('avl_copy', models.PositiveIntegerField()),
                ('added_on', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='book', to='libraryApp.category')),
            ],
        ),
    ]
