# Generated by Django 5.2.8 on 2025-11-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0003_category_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
