# Generated by Django 5.2.8 on 2025-11-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0004_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='books/default.jpeg', null=True, upload_to='books'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='profile/default.jpeg', null=True, upload_to='profile'),
        ),
    ]
