# Generated by Django 5.2.8 on 2025-11-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0006_book_user_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avl_copy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_copy',
            field=models.IntegerField(),
        ),
    ]
