# Generated by Django 5.2.8 on 2025-11-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0008_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='books/default.jpg', null=True, upload_to='books'),
        ),
    ]
