# Generated by Django 5.2.8 on 2025-11-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0009_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='profile/default.jpg', null=True, upload_to='profile'),
        ),
    ]
